"""Cut a v2 modular style (4 ChatGPT sheets) into a 16px tile atlas plus named multi-tile objects.

usage: build-style-v2.py <style-dir> [atlas.ts]   (reads <style-dir>/v2/<prefix>-1..4.png and <style-dir>/v2/objects.json)
writes <style-dir>/v2/build/atlas.png and atlas.json
"""
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage

T = 16


def load_sheet(path):
    im = Image.open(path).convert("RGBA")
    a = np.array(im).astype(int)
    r, g, b, al = a[..., 0], a[..., 1], a[..., 2], a[..., 3]
    bg = (al < 200) | ((abs(r - 255) + g + abs(b - 255)) < 120) | ((r + g + b) < 40)
    return a, bg


def components(a, bg):
    fg = ndimage.binary_opening(~bg, iterations=2)
    lab, _ = ndimage.label(fg)
    out = []
    for i, s in enumerate(ndimage.find_objects(lab)):
        if (s[0].stop - s[0].start) * (s[1].stop - s[1].start) < 900:
            continue
        mask = ndimage.binary_erosion(lab[s] == i + 1, iterations=1)
        rgba = a[s].copy().astype(np.uint8)
        rgba[..., 3] = np.where(mask, 255, 0)
        out.append({"cx": (s[1].start + s[1].stop) / 2, "cy": (s[0].start + s[0].stop) / 2, "img": Image.fromarray(rgba, "RGBA")})
    return out


def fit(img, w, h, anchor="bottom"):
    """Scale to fill a w x h tile footprint, keeping aspect, centred horizontally, standing on the bottom edge."""
    W, H = w * T, h * T
    k = min(W / img.width, H / img.height)
    s = img.resize((max(1, round(img.width * k)), max(1, round(img.height * k))), Image.LANCZOS)
    a = np.array(s)
    a[..., 3] = np.where(a[..., 3] > 110, 255, 0)
    s = Image.fromarray(a, "RGBA")
    out = Image.new("RGBA", (W, H))
    y = H - s.height if anchor == "bottom" else (0 if anchor == "top" else (H - s.height) // 2)
    out.alpha_composite(s, ((W - s.width) // 2, y))
    return out


def stretch(img, w, h):
    s = img.resize((w * T, h * T), Image.LANCZOS)
    a = np.array(s)
    a[..., 3] = np.where(a[..., 3] > 110, 255, 0)
    return Image.fromarray(a, "RGBA")


def main(style_dir):
    root = Path(style_dir) / "v2"
    spec = json.loads((root / "objects.json").read_text())
    prefix = spec["prefix"]
    sheets = {n: load_sheet(root / f"{prefix}-{n}.png") for n in (1, 2, 3, 4)}
    comps = {n: components(*sheets[n]) for n in (2, 3, 4)}

    images = {}
    for name, o in spec["objects"].items():
        n = o["sheet"]
        if "box" in o:
            x0, y0, x1, y1 = o["box"]
            a, bg = sheets[n]
            crop = a[y0:y1, x0:x1].copy().astype(np.uint8)
            crop[..., 3] = np.where(bg[y0:y1, x0:x1], 0, 255)
            img = Image.fromarray(crop, "RGBA")
        else:
            img = min(comps[n], key=lambda c: (c["cx"] - o["at"][0]) ** 2 + (c["cy"] - o["at"][1]) ** 2)["img"]
        w, h = o["size"]
        images[name] = stretch(img, w, h) if o.get("stretch") else fit(img, w, h, o.get("anchor", "bottom"))

    for name, o in spec.get("split", {}).items():
        src = images.pop(name)
        for i, part in enumerate(o):
            images[part] = src.crop((i * T, 0, (i + 1) * T, src.height))

    tiles, index, objects = [], {}, {}
    for name, img in images.items():
        grid = []
        for ty in range(img.height // T):
            row = []
            for tx in range(img.width // T):
                t = img.crop((tx * T, ty * T, tx * T + T, ty * T + T))
                if t.getchannel("A").getbbox() is None:
                    row.append(-1)
                    continue
                key = t.tobytes()
                if key not in index:
                    index[key] = len(tiles)
                    tiles.append(t)
                row.append(index[key])
            grid.append(row)
        objects[name] = grid

    cols = 32
    rows = -(-len(tiles) // cols)
    atlas = Image.new("RGBA", (cols * T, rows * T))
    for i, t in enumerate(tiles):
        atlas.paste(t, ((i % cols) * T, (i // cols) * T))
    out = root / "build"
    out.mkdir(exist_ok=True)
    atlas.save(out / "atlas.png", optimize=True)
    (out / "atlas.json").write_text(json.dumps({"tile": T, "columns": cols, "count": len(tiles), "objects": objects}, separators=(",", ":")))
    if len(sys.argv) > 2:
        data = json.dumps({"columns": cols, "rows": rows, "objects": objects}, separators=(",", ":"))
        header = f"// Generated by scripts/build-style-v2.py from {root.as_posix()}; do not edit."
        Path(sys.argv[2]).write_text(header + "\n" + f"export const ATLAS = {data} as const;" + "\n")
    print(f"{len(objects)} objects, {len(tiles)} unique tiles, atlas {atlas.size}")


if __name__ == "__main__":
    main(sys.argv[1])
