import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";
import { PAGE_ROUTE } from "./shared/office.js";
import { DEFAULTS } from "./shared/settings.js";

const manifest: PaperclipPluginManifestV1 = {
  id: "paperclip-office",
  apiVersion: 1,
  version: "0.1.0",
  displayName: "Office",
  description: "Your company as a live pixel office: every agent at a desk, work moving between them",
  author: "Kshitij Mittal",
  categories: ["ui"],
  capabilities: [
    "agents.read",
    "issues.read",
    "issue.comments.read",
    "approvals.read",
    "database.namespace.migrate",
    "database.namespace.read",
    "metrics.write",
    "agent.tools.register",
    "ui.page.register",
    "ui.sidebar.register",
    "ui.dashboardWidget.register",
  ],
  database: {
    namespaceSlug: "office",
    migrationsDir: "migrations",
    coreReadTables: ["heartbeat_runs", "issue_comments", "cost_events", "budget_incidents"],
  },
  entrypoints: {
    worker: "./dist/worker.js",
    ui: "./dist/ui",
  },
  tools: [
    {
      name: "office_status",
      displayName: "Office status",
      description: "Who is idle, stuck, or overloaded right now, optionally filtered by department or state.",
      parametersSchema: {
        type: "object",
        properties: {
          department: { type: "string", description: "Restrict to one department name." },
          state: { type: "string", enum: ["idle", "thinking", "working", "blocked"], description: "Restrict to one state." },
        },
      },
    },
  ],
  instanceConfigSchema: {
    type: "object",
    properties: {
      theme: {
        type: "string",
        title: "Theme",
        description: "The office's visual style.",
        enum: ["office", "brooklyn99", "generated"],
        default: DEFAULTS.theme,
      },
      stuckMinutes: {
        type: "number",
        title: "Stuck after (minutes)",
        description: "An agent with a live run and no output for this long is marked stuck.",
        default: DEFAULTS.stuckMinutes,
        minimum: 1,
        maximum: 240,
      },
      pollSeconds: {
        type: "number",
        title: "Refresh interval (seconds)",
        description: "How often the office polls for new data.",
        default: DEFAULTS.pollSeconds,
        minimum: 2,
        maximum: 60,
      },
      idleRoaming: {
        type: "string",
        title: "Idle roaming",
        description: "Whether idle agents wander the floor or stay seated at their desks.",
        enum: ["off", "calm", "lively"],
        default: DEFAULTS.idleRoaming,
      },
      chatter: {
        type: "boolean",
        title: "Chatter",
        description: "Show ambient small talk (gossip, cheers, errands) between agents.",
        default: DEFAULTS.chatter,
      },
      bubbles: {
        type: "string",
        title: "Thought bubbles",
        description: "What each agent's thought bubble shows.",
        enum: ["activity", "issue", "output", "none"],
        default: DEFAULTS.bubbles,
      },
      castStyle: {
        type: "string",
        title: "Cast style",
        description: "The character roster used for agents on the floor.",
        enum: ["office", "neutral"],
        default: DEFAULTS.castStyle,
      },
      language: {
        type: "string",
        title: "Language",
        description: "Language for on-screen office text.",
        enum: ["en", "ar", "zh-CN"],
        default: DEFAULTS.language,
      },
      showOrgPanel: {
        type: "boolean",
        title: "Show org panel",
        description: "Show the department/org-chart panel below the office.",
        default: DEFAULTS.showOrgPanel,
      },
      showStateBoard: {
        type: "boolean",
        title: "Show state board",
        description: "Show the per-agent state table below the office.",
        default: DEFAULTS.showStateBoard,
      },
      activityFeed: {
        type: "boolean",
        title: "Activity feed",
        description: "Show the collapsible activity feed below the office.",
        default: DEFAULTS.activityFeed,
      },
      activityWindowHours: {
        type: "number",
        title: "Activity window (hours)",
        description: "How far back the activity feed looks.",
        default: DEFAULTS.activityWindowHours,
        minimum: 1,
        maximum: 168,
      },
      activityLimit: {
        type: "number",
        title: "Activity feed limit",
        description: "Maximum number of activity events shown.",
        default: DEFAULTS.activityLimit,
        minimum: 10,
        maximum: 500,
      },
      officeStatusTool: {
        type: "boolean",
        title: "Office status agent tool",
        description: "Let agents call the office_status tool to check who is idle, stuck, or overloaded.",
        default: DEFAULTS.officeStatusTool,
      },
      overloadThreshold: {
        type: "number",
        title: "Overload threshold",
        description: "An agent with this many or more open issues is reported as overloaded.",
        default: DEFAULTS.overloadThreshold,
        minimum: 1,
        maximum: 50,
      },
      heatmap: {
        type: "boolean",
        title: "Bottleneck heatmap",
        description: "Color each occupied desk by that agent's queue depth.",
        default: DEFAULTS.heatmap,
      },
      heatLow: {
        type: "number",
        title: "Heatmap low threshold",
        description: "Queue depth at or above this many open issues turns a desk amber.",
        default: DEFAULTS.heatLow,
        minimum: 1,
        maximum: 999,
      },
      heatHigh: {
        type: "number",
        title: "Heatmap high threshold",
        description: "Queue depth at or above this many open issues turns a desk red.",
        default: DEFAULTS.heatHigh,
        minimum: 1,
        maximum: 999,
      },
      search: {
        type: "boolean",
        title: "Agent search",
        description: "Press / to search and jump to an agent.",
        default: DEFAULTS.search,
      },
      bottleneckCount: {
        type: "number",
        title: "Bottleneck list size",
        description: "How many agents to show in the Bottlenecks mini list.",
        default: DEFAULTS.bottleneckCount,
        minimum: 1,
        maximum: 20,
      },
      showCost: {
        type: "boolean",
        title: "Show cost",
        description: "Show cost per agent and department.",
        default: DEFAULTS.showCost,
      },
      costWindowDays: {
        type: "number",
        title: "Cost window (days)",
        description: "How many trailing days of cost to sum per agent and department.",
        default: DEFAULTS.costWindowDays,
        minimum: 1,
        maximum: 90,
      },
      costMetric: {
        type: "string",
        title: "Spend shown as",
        description: "auto shows tokens when there is no dollar spend (subscription runs record $0).",
        enum: ["auto", "dollars", "tokens"],
        default: DEFAULTS.costMetric,
      },
      budgetAlerts: {
        type: "boolean",
        title: "Budget alerts",
        description: "Show a banner for open budget incidents and mark agents over budget.",
        default: DEFAULTS.budgetAlerts,
      },
      askBoard: {
        type: "boolean",
        title: "ASK ME board",
        description: "Pin each pending approval as a note on the office ASK ME board; clicking the board opens the inbox.",
        default: DEFAULTS.askBoard,
      },
    },
  },
  ui: {
    slots: [
      { type: "page", id: "office", displayName: "Office", exportName: "OfficePage", routePath: PAGE_ROUTE },
      { type: "sidebar", id: "nav", displayName: "Office", exportName: "SidebarLink" },
      { type: "dashboardWidget", id: "summary", displayName: "Office", exportName: "OfficeWidget" },
    ],
  },
};

export default manifest;
